### PR TITLE
add nil check on RepresentationEditor#add_link

### PR DESCRIPTION
**Pull request by adherr**
empty string hrefs are bad

### CODE REVIEW

**Comment by pezra** [comment]
can you bump the version number, please

**Comment by adherr** [comment]
Did I bump it hard enough?

**Comment by pezra** [comment]
interesting question. probably not. i think this is probably a breaking change so the major version should get bumped.

**Comment by adherr** [comment]
Is it a breaking change worth making?

**Comment by adherr** [comment]
I amended the bump commit, so you probably didn't get a notification of file changes. Here's one.

**Comment by pezra** [comment]
released as 5.0.0

**Pull request merged**
