### PR TITLE
Use http.rb ~> 1.0.0

### PR DESCRIPTION
**Pull request by jeromegn**
I did the minor modifications for the http gem v1.0.x to work.

It brings a few improvements: https://github.com/httprb/http/blob/master/CHANGES.md#100-2015-12-25

### CODE REVIEW

**Comment by pezra** [comment]
i think this update is a great idea. however, would it be possible to maintain compatibility with the http.rb > 0.8 & < 2.0? The 0.9 release removed http caching which i need for some of my projects.

**Comment by ivoanjo** [comment]
Any news on this one?

Upstream is now at `2.0.2` and includes a number of cool fixes, it would be awesome if this could be applied.

**Comment by pezra** [comment]
I still have the same problem with this PR as before. HTTP.rb still doesn't support caching nor are there, to my knowledge, any third party libraries for it that provide that functionality. I'd love to move to the newest version but caching is integral to every successful API implementation I've ever done. I am not willing to upgrade until we have a caching solution.

**Comment by tjsousa** [comment]
Do you guys think a backwards compatibility approach like this one would be feasible: https://github.com/jeromegn/hal-client/pull/1

It was tested against http.rb versions `0.7.4`, `0.9.9` and `1.0.4` and all tests are passing.

**Comment by pezra** [comment]
@tjsousa, that looks great! I'd merge a PR to that effect. :smile:

**Comment by tjsousa** [comment]
I opened the PR against @jeromegn's fork since he had the work of actually inspecting the code to make it `~> 1.0.0` compatible. If he accepts it and rebase the changes into this PR, I'm happy with that.

Otherwise I can open a PR against the master branch here as well. :)

**Comment by jeromegn** [comment]
I merged @tjsousa in my branch. Nice work there! (I didn't even remember I had made a PR)

**Comment by lucke84** [comment]
@tjsousa so the way it'd work is that the `hal-client` gem will support any version of the `http` gem between 0.7 and 2.0 (excluded), then it's up to you to include in your project the `http` gem explicitly (as well as the version you desire)?

**Comment by jeromegn** [comment]
@lucke84 It will install the latest version of the gem compatible with all your other gems. If you've explicitly included the `http` gem with a specific version that is between 0.7 and 2.0.0 (exclusive), then it'll be satisfied and use that. Else it'll install 1.x.x if all other gem dependencies are good with it.

**Comment by pezra** [comment]
@jeromegn, looking good. If you rebase on to master i'll merge it.

**Comment by jeromegn** [comment]
Hmm I rebased, but things are weird now. A local diff shows everything is good (2 files changed), but for some reason there are 19 files changed here.

**Comment by pezra** [comment]
Worse case you could cherry pick your two commits into a new branch

**Comment by pezra** [comment]
@jeromegn, any chance of landing this PR?

**Comment by ivoanjo** [comment]
I'm preparing another take on this in branch https://github.com/ivoanjo/hal-client/tree/http-one-oh-try2 , but I haven't tested it very much so I wanted to do that before submitting it.

**Comment by jeromegn** [comment]
More than happy if somebody else wants to tackle it. I won't be using this project in the near future and I won't be as interested as contributing.

I haven't had much time lately, I'm starting my own company and resolving git merge weirdness (well, they are my weirdnesses) is making it hard to get motivated ;)

**Comment by pezra** [comment]
Fixed by #59

**Pull request closed without merging**
